version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: leao-escuta-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=@@@LeaoSasa1!
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data:
    driver: local
